upstream:
  server:
    host: localhost
    port: 3000

downstream:
  db:
    host: 0.0.0.0
    port: 5432
    database: db
    user: postgres
    password: postgres

server:
  host: localhost
  port: 8082